### ISSUE TITLE
Exporting protected files

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/twinkle#11]
It's probably the case that all files that are protected warrant syncronising and probably nothing else.  So we should expand the yaml to say:

```yaml
protect:
  paths:
    - emails.db
    - contributions
  dest: <path on host>
  frequency: hourly
  delete: true
```

The paths should be exported using rsync to the destination on the host - use `rsync`, optionally with `--delete` (indicated with the `delete` flag)

For the actual schedule use `cron` on the host, write to the _user_ crontab (if we can get sufficient permissions in the job itself but I think that's fine).  We'll write out the actual cron jobs into `<projroot>/cron` and use the same approach as the auth for doing deletions there.  Filtering out unwanted cron jobs should be ok too
