### ISSUE TITLE
Provision using PAT

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/twinkle#13]
For complex dependencies of private repos a deploy key is not enough.  It might be possible to get quite a long way with deploy keys if the drat provisioning is made a little more clever (checking for a deploy key for every spec - this is a change in provisionr and requires _cloning_ the repo not downloading the archive).

Users need to generate a PAT with the `user` scope.  It's possible that we can add a robot user to the `mrc-ide` repo and use that, but it's not clear that's an awful lot better, unless we're good about making it only have readonly scope.

```
./scripts/add_github_pat username
```

This will store the PAT at something like

```
/secret/<root>/github_pat/<username>
```

then 
```yaml
apps:
  myapp:
    ...
    auth:
      type: github_pat
      user: <username>
```
