### ISSUE TITLE
Applications need a concept of owner

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/twinkle#26]

**Comment by richfitz** [comment]
I think that an optional key:

```yaml
  eppasmviewer:
    type: github
    spec: mrc-ide/eppasmviewer/inst/shiny/eppasmviewer
    auth:
      type: deploy_key
    groups:
      - dide-internal
    admin:
      - jeff
```

should do the trick
